### ISSUE TITLE
大佬能分享Dockerfile学习学习一下吗

### ISSUE THREAD

**Issue by kenuoseclab** [0xgkd/awvs#1]
大佬能分享Dockerfile学习学习一下吗

**Comment by 0xgkd** [comment]
我是在Ubuntu 18.04镜像的基础之上，手动安装awvs，再破解打包的，Dockerfile的话不可避免地要引入额外依赖库以及安装缓存之类，导致每个Layer层都会大上不少，最终镜像的体积都不小

**Comment by 0xgkd** [comment]
> 大佬能分享Dockerfile学习学习一下吗

我是在Ubuntu 18.04镜像的基础之上，手动安装awvs，再破解打包的，Dockerfile的话不可避免地要引入额外依赖库以及安装缓存之类，导致每个Layer层都会大上不少，最终镜像的体积都不小

**Comment by cqkenuo** [comment]
> > 大佬能分享Dockerfile学习学习一下吗
> 
> 我是在Ubuntu 18.04镜像的基础之上，手动安装awvs，再破解打包的，Dockerfile的话不可避免地要引入额外依赖库以及安装缓存之类，导致每个Layer层都会大上不少，最终镜像的体积都不小

好的感谢大佬
