### ISSUE TITLE
使用 这个镜像跑引擎的时候会显示注册失败

### ISSUE THREAD

**Issue by pythonSB** [0xgkd/awvs#12]
web返回的错误

The Main Installation responded with error [Worker is not reachable]

后端错误

2024-09-20 09:25:56,577: ERROR helpers.licensing.license invalid checksum

离谱 不知道什么原因 
配置文件中配置的是engineonly=1

**Comment by 0xgkd** [comment]
> web返回的错误
> 
> The Main Installation responded with error [Worker is not reachable]
> 
> 后端错误
> 
> 2024-09-20 09:25:56,577: ERROR helpers.licensing.license invalid checksum
> 
> 离谱 不知道什么原因 配置文件中配置的是engineonly=1

@pythonSB 已更新

**Comment by pythonSB** [comment]
ok，之前已经解决，但是还是感谢更新
